### ISSUE TITLE
NPM Module Resource

### ISSUE THREAD

**Issue by Skillz4Killz** [quranacademy/digital-quran-docs#2]
Asalamoalaikum Wa Rahmatullahi Wa Barakatuhu

Have you considered having an NPM module instead of an API? An API comes with a few downsides:
1. Costs of hosting
2. APIs can go down meaning all users lose functionality.
3. API's need API keys meaning in order to get access to the data, I first need to make an account register for a key.
4. Store the API Key in a private config file and create env variables for deployment servers.

On the other hand if it was a NPM module of exported Typescript files, we would avoid all these issues and also get other benefits.
1. NPM module means no costs of hosting an API
2. NPM module can never go down all users would have it inside their `node_modules`. This would also be a good performance boost as no one needs to send out requests to an api.
3. No need to make, register API Keys => just `npm i quranacademy`(as an example)
4. No need to store anything or create env vars because there is no secret keys.
5. Typescript would automatically create static typings for all the files so that anyone using a decent IDE will get autocomplete features.

**Comment by murad073** [comment]
Good point. NPM module can be another additional resource, but it can't be a replacement for a RESTful API. Not all api client in the world is JavaScript/Node.js platform.  There are Java, .NET, Ruby, Python, C++, ..... platform you can't ignore.

**Comment by rguliev** [comment]
وعليكم السلام ورحمة الله وبركاته

@Skillz4Killz Thanks for the suggestion. As @murad073 already pointed out, npm package can not be a complete replacement for an API. Another point is that we can not put all the content (translations, tafseers, etc.) in a package because it would be too big over time. 

On the other hand, we agree that in some cases it is more convenient to use a package. In sha'Allah, we are going to add some helper scripts/packages (for the most popular languages) which will simplify the most common tasks. Like parsing of content files or working with API. You can participate in that if you like. Any help is appreciated:)

**Comment by Arvant** [comment]
salam
in node js Express.js
in php lumen,laravel.codeigniter
in python flask
i think php is Inexpensive

**Comment by rguliev** [comment]
وعليكم السلام

@Arvant What do you mean? Sorry did not get your point)

**Comment by Skillz4Killz** [comment]
Very good point. I suppose just an additional NPM Packages as opposed to replacing it would be the best-case scenario.

@rguliev Would be happy to help with an API wrapper for Javascript/Typescript or any other JS/TS needs

**Comment by Imangazaliev** [comment]
We will publish files with translations and other resources on GitHub, in shaa Allah, so any developer, who does not want to use the API, will can just download these files.
